### ISSUE TITLE
Modificar recentSearch 

### ISSUE THREAD

**Issue by livchits** [livchits/kindleBueno#28]
**Hacer los cambios a partir del branch _recentKeywords_**

1. Cambiar la lógica para Implementar un _buffer_: 
- Guardar las búsquedas en un array una despúes de otra.
- Al llegar a las cinco búsquedas revertir el orden del array y comenzar a sumar las búsquedas al principio y elimnando la última (que es ls más antigua)

**Comment by mborroni** [comment]
Acá tengo una duda, no es lo mismo hacer lo que hiciste vos de eliminar el primer elemento?

**Comment by livchits** [comment]
Me parece (porque no sé si lo entendí bien) que es levemente distinto: debería quedar la úlitma búsqueda al principio, pero sólo a partir de la la quinta.

O sea, empezás con el array vacío. Y le vas pusheando las keywords:
`[kw1, kw2, kw3]`

Cuando llegás a cinco el orden se invierte: 
`[kw5, kw4, kw3, kw2, kw1]`

Y después empezás a agregar al principio:
`[kw6, kw5, kw4, kw3, kw2]`

Igual tampoco estoy totalmente seguro 😐
