### ISSUE TITLE
correcciones

### ISSUE THREAD

**Issue by nhsz** [livchits/kindleBueno#45]
- [x] para actualizar [`this.readBooks`](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L51) y [`this.notReadYetBooks`](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L39) alcanza con sumar y restar. La solución con `reduce` funciona, pero están haciendo muchos cálculos innecesarios y va a ser cada vez más costoso a medida que se agreguen libros

- [x] [en lugar de preguntar por la longitud](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L22) de `_library`, pueden aprovechar la info que les da `_current` y `_next`, además es más clara la intención de esta forma

- [x] Usar el operador de negación [en lugar de comparar con un booleano](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L78)

- [x] falta implementar el método [`filterBy`](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L111)

- [x] [`Buffer`](https://github.com/livchits/kindleBueno/blob/0919a6969e5b6d97b1d9ab82dd45972784c2d375/Kindle.js#L129) debería tener un método en su interfaz que permita obtener los recientes, de forma más declarativa

- [x] La [búsqueda](https://github.com/livchits/kindleBueno/blob/master/Search.js) debería ser funcionalidad del Kindle en si, no una clase aparte. En todo caso pueden tener un archivo para funciones utilitarias sueltas

**Comment by livchits** [comment]
2. Ver [fixAdd](https://github.com/livchits/kindleBueno/tree/fixAdd).
3. Ver [fixUpdateNextEbook](https://github.com/livchits/kindleBueno/tree/fixUpdateNextEbook)
5. Ver [fixBuffer](https://github.com/livchits/kindleBueno/tree/fixBuffer)
